#!/usr/bin/env python3
"""Validate and normalize timestamped film observations.

The JSONL boundary is intentionally modest: one observation object per line.
It preserves model/annotator provenance while rejecting malformed records before
anything is projected into the typed Mercury episode model.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from typing import Any, Iterable, TextIO

CHANNELS = {"visual", "audio", "dialogue", "music", "editing", "context"}


@dataclass(frozen=True)
class FilmObservation:
    observation_id: str
    start_ms: int
    end_ms: int
    channel: str
    content: str
    confidence: float
    provenance: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "id": self.observation_id,
            "start_ms": self.start_ms,
            "end_ms": self.end_ms,
            "channel": self.channel,
            "content": self.content,
            "confidence": self.confidence,
            "provenance": self.provenance,
        }


def _number(value: Any, field: str) -> int:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"{field} must be a number")
    if int(value) != value:
        raise ValueError(f"{field} must be an integer")
    return int(value)


def _confidence(value: Any) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError("confidence must be a number")
    result = float(value)
    if not 0.0 <= result <= 1.0:
        raise ValueError("confidence must be between 0 and 1")
    return result


def normalize_observation(record: dict[str, Any]) -> FilmObservation:
    required = {"id", "start_ms", "end_ms", "channel", "content", "confidence", "provenance"}
    missing = required - record.keys()
    if missing:
        raise ValueError(f"missing fields: {', '.join(sorted(missing))}")
    observation_id = record["id"]
    channel = record["channel"]
    content = record["content"]
    provenance = record["provenance"]
    if not isinstance(observation_id, str) or not observation_id:
        raise ValueError("id must be a non-empty string")
    if channel not in CHANNELS:
        raise ValueError(f"channel must be one of: {', '.join(sorted(CHANNELS))}")
    if not isinstance(content, str):
        raise ValueError("content must be a string")
    if not isinstance(provenance, str) or not provenance:
        raise ValueError("provenance must be a non-empty string")
    start_ms = _number(record["start_ms"], "start_ms")
    end_ms = _number(record["end_ms"], "end_ms")
    if start_ms < 0 or end_ms < start_ms:
        raise ValueError("interval must satisfy 0 <= start_ms <= end_ms")
    return FilmObservation(
        observation_id, start_ms, end_ms, channel, content,
        _confidence(record["confidence"]), provenance,
    )


def read_jsonl(stream: Iterable[str]) -> list[FilmObservation]:
    observations: list[FilmObservation] = []
    seen: set[str] = set()
    for line_number, line in enumerate(stream, 1):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        try:
            record = json.loads(line)
            if not isinstance(record, dict):
                raise ValueError("record must be a JSON object")
            observation = normalize_observation(record)
            if observation.observation_id in seen:
                raise ValueError(f"duplicate id: {observation.observation_id}")
            seen.add(observation.observation_id)
            observations.append(observation)
        except (json.JSONDecodeError, ValueError) as error:
            raise ValueError(f"line {line_number}: {error}") from error
    return observations


def _mercury_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def generate_mercury_module(observations: list[FilmObservation], module_name: str = "film_annotation_fixture") -> str:
    if not module_name.replace("_", "a").isalnum() or not module_name[0].islower():
        raise ValueError("module_name must be a lowercase Mercury identifier")
    lines = [
        "% Generated by film_annotations.py; do not edit by hand.",
        f":- module {module_name}.",
        "",
        ":- interface.",
        "",
        ":- import_module film_episode.",
        ":- import_module list.",
        "",
        ":- func observations = list(film_episode.observation).",
        "",
        ":- implementation.",
        "",
        "observations = [",
    ]
    rendered = []
    for observation in observations:
        rendered.append(
            "    film_episode.observation(%s, %d, %d, %s, %s, %.17g, %s)"
            % (
                _mercury_string(observation.observation_id),
                observation.start_ms,
                observation.end_ms,
                observation.channel,
                _mercury_string(observation.content),
                observation.confidence,
                _mercury_string(observation.provenance),
            )
        )
    lines.append(",\n".join(rendered))
    lines.extend([
        "].",
        "",
        f":- end_module {module_name}.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", nargs="?", help="JSONL file; stdin if omitted")
    parser.add_argument("--mercury", metavar="PATH", help="write a Mercury fixture module")
    parser.add_argument("--module", default="film_annotation_fixture")
    args = parser.parse_args()
    stream: TextIO
    with open(args.path, encoding="utf-8") if args.path else sys.stdin as stream:
        observations = read_jsonl(stream)
    if args.mercury:
        with open(args.mercury, "w", encoding="utf-8") as output:
            output.write(generate_mercury_module(observations, args.module))
    else:
        for observation in observations:
            print(json.dumps(observation.to_dict(), sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
