% Generated by film_annotations.py; do not edit by hand.
:- module film_annotation_fixture.

:- interface.

:- import_module film_episode.
:- import_module list.

:- func observations = list(film_episode.observation).

:- implementation.

observations = [
    film_episode.observation("o1", 0, 12000, visual, "confined industrial interior", 0.97999999999999998, "annotator:fixture"),
    film_episode.observation("o2", 0, 12000, audio, "continuous industrial drone", 0.95999999999999996, "annotator:fixture"),
    film_episode.observation("o3", 13000, 19000, visual, "small domestic room with bodily imagery", 0.91000000000000003, "annotator:fixture")
].

:- end_module film_annotation_fixture.
