% Generated by film_annotations.py; do not edit by hand.
:- module meshes_gold_scene_fixture.

:- interface.

:- import_module film_episode.
:- import_module list.

:- func observations = list(film_episode.observation).
:- func relations = list(film_episode.observation_relation).

:- implementation.

observations = [
    film_episode.observation("m01", 0, 12000, visual, "woman-shaped figure traverses an exterior path toward a house", 0.71999999999999997, "annotator:nyc;review:pending"),
    film_episode.observation("m02", 7000, 16000, visual, "flower is visible as the figure approaches the house", 0.68000000000000005, "annotator:nyc;review:pending"),
    film_episode.observation("m03", 17000, 26000, visual, "hand manipulates or carries a key near the house entrance", 0.64000000000000001, "annotator:nyc;review:pending"),
    film_episode.observation("m04", 27000, 41000, visual, "figure moves through the house interior and ascends stairs", 0.69999999999999996, "annotator:nyc;review:pending"),
    film_episode.observation("m05", 32000, 42000, visual, "mirror-faced or otherwise obscured figure appears in the interior", 0.60999999999999999, "annotator:nyc;review:pending"),
    film_episode.observation("m06", 31500, 42500, audio, "surrealist score continues while the obscured figure is present", 0.66000000000000003, "annotator:nyc;review:pending"),
    film_episode.observation("m07", 43000, 50000, editing, "cut or transition separates the interior encounter from the next beat", 0.59999999999999998, "annotator:nyc;review:pending"),
    film_episode.observation("m08", 0, 50000, context, "opening motif sequence from exterior approach through interior encounter", 0.57999999999999996, "annotator:nyc;review:pending")
].

relations = [
    film_episode.observation_relation("m01", overlaps, "m02", 0.75, "annotator:nyc;review:pending"),
    film_episode.observation_relation("m02", before, "m03", 0.81999999999999995, "derived:intervals;review:pending"),
    film_episode.observation_relation("m03", before, "m04", 0.81999999999999995, "derived:intervals;review:pending"),
    film_episode.observation_relation("m04", overlaps, "m05", 0.78000000000000003, "annotator:nyc;review:pending"),
    film_episode.observation_relation("m05", synchronized_with, "m06", 0.72999999999999998, "annotator:nyc;review:pending"),
    film_episode.observation_relation("m07", after, "m05", 0.83999999999999997, "derived:intervals;review:pending"),
    film_episode.observation_relation("m03", during, "m08", 0.90000000000000002, "derived:intervals;review:pending"),
    film_episode.observation_relation("m02", contrasts_with, "m06", 0.45000000000000001, "annotator:nyc;review:pending")
].

:- end_module meshes_gold_scene_fixture.
